name: heart Disease Prediction
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Install dependecies
        run: |
          pip install -r requirements.txt
      - name: Load data
        env:
          REPO_TOKEN: ${{ secrets.DVC_MLOPS_TOKEN }}
        run: |
          # DVC
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user GowthamiWudaru
          dvc pull -r origin processed.cleveland.data
      - name: Train model
        run: |
          # Your ML workflow goes here
          dvc repro
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          echo "## Model Metrics" > report.md
          # metrics compare
          git fetch --prune
          dvc metrics diff main --targets metrics.json --show-md > report.md
          cml-send-comment report.md
